# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4dc7387ebf933c7b92bfda5c3c0bf5829c66f3bf313a6d302ef8815a375ce91e469bc0ef94b5af275598fd73e0b07c3777c41117b644a39ad26fb4bebb670e5

test:
  secret_key_base: 904c8a337a40913e2a61eb0f5284f6797603bcd8b7a9a931093dad66a9f087dc5cb3bda09444efb4f5974f948aa71ca32a4d34d0c6bfcdc8afcc590b0e87cb70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
